name: LinterWorkflow

on:
  push

jobs:
  type-check:
    name: Type-Check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
      - name: Install node packages
        working-directory: ./naxt-electron
        run: |
          npm install
        env:
          CI: true
      - name: Check Code Quality
        working-directory: ./naxt-electron
        run: |
          npm run prettier:check
          npm run eslint:check
        env:
          CI: true