name: Remove old artifacts

on:
  schedule:
    # Every day at 1am
    - cron: '00 1 26 * *'

jobs:
  remove-old-artifacts:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1.2.0
      with:
        age: '7 day'
        # Optional inputs
        # skip-tags: true
        # skip-recent: 6
